version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
    node/test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                    steps:
                        - run: sudo npm install -g npm@latest
                        - run: sudo npm install
                        - run: npm run test


workflows:
  node-tests:
    jobs:
      - node/test
